### ISSUE TITLE
Home Assistant 0.92.0 Betas. Some new error and a deprecation

### ISSUE THREAD

**Issue by dreimer1986** [rgruebel/ha_zigbee2mqtt_networkmap#8]
In my log these show up now:

WARNING (MainThread) [homeassistant.helpers.service] Unable to find services.yaml for the zigbee2mqtt_networkmap integration

--and--

Signature of MQTT msg_callback 'custom_components.zigbee2mqtt_networkmap.message_received' is deprecated

**Comment by h4nc** [comment]
@rgruebel I have the same issue. Also I noticed that the "Update now" Button doesn't refresh the page anymore.

**Comment by h4nc** [comment]
I also see this 

`Received message for unregistered webhook *******`

**Comment by sermayoral** [comment]
Same here.

Thanks!!

**Comment by Snake1980** [comment]
Same here

**Comment by andriej** [comment]
Same here

**Comment by wimpie007** [comment]
same here. (of course)

**Comment by rgruebel** [comment]
Should be fixed with the last commit. Apparently each component now needs its own folder. In my case everything works again, please report if there are still issues.

**Comment by h4nc** [comment]
Thanks, the update button works again. And also I don't get that webhook error any more. 

But I still get this Error:

`Unable to find services.yaml for the zigbee2mqtt_networkmap integration`

This was also a new one coming with 0.92

**Comment by rgruebel** [comment]
May be you forgot to copy the Services. Yaml?

**Comment by h4nc** [comment]
That's weird. You are right the services.yaml was missing, but I copied the whole folder to my direction.

Anyway with the zip-download now there is this service.yaml file, and after a restart this error will be gone. Thanks
